disabled_rules:
- file_length
- force_cast
- identifier_name
- line_length
- type_body_length
- type_name
opt_in_rules:
- file_header
- cyclomatic_complexity

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  GameIconsTests
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\.\d{1,2}\.\d{2}\.
                    \/\/  Copyright © \d{4} Quantum\. All rights reserved\.
                    \/\/
cyclomatic_complexity: 5
function_body_length: 15
function_parameter_count: 4
