disabled_rules:
- file_length
- force_cast
- identifier_name
- line_length
- type_body_length
- type_name
opt_in_rules:
- cyclomatic_complexity
excluded:
- GameIconsTests/GeneratedMocks.swift
cyclomatic_complexity: 5
function_body_length: 15
function_parameter_count: 4
